[platformio]
extra_configs = secret.ini

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_port = COM3
build_flags =
    -DWIFI_SSID=\"${wifi_secrets.ssid}\"
    -DWIFI_PASS=\"${wifi_secrets.pass}\"